name: 0.x Release new version

on:
  workflow_dispatch:
    inputs:
      majorRelease:
        required: false
        description: 'Release as version. Example values are: minor, major, 5.6.1, 1.0.0. Leave empty for regular release.'

jobs:
  release:
    uses: ./.github/workflows/release-workflow.yml
    with:
      branch: 0.x
      majorRelease: ${{ inputs.majorRelease }}
